### ISSUE TITLE
Center sensor Data

### ISSUE THREAD

**Issue by DrJeff** [thomasloven/lovelace-useful-markdown-card#1]
Is there a way to center the sensor text data in the card? Using [[ sensor.some-sensor ]] but want it centered in the card

**Comment by thomasloven** [comment]
```yaml
- type: custom:useful-markdown-card
  content: >
    <center>[[ sensor.some-sensor ]] </center>
```
