### ISSUE TITLE
Trying to use 2 markdown in horizontal

### ISSUE THREAD

**Issue by mcfrojd** [thomasloven/lovelace-useful-markdown-card#10]
When i try to use 2 markdown cards in a horizontal stack (with card-modder) i get an error.
**Error:**

```
found duplicate anchor 'markdown'; first occurence in "/config/ui-lovelace.yaml", line 71, column 28 second occurence in "/config/ui-lovelace.yaml", line 82, column 28
```

**yaml example:**

```
          - type: horizontal-stack
            cards:
              - type: custom:card-modder
                card:
                  type: custom:useful-markdown-card
                  content: &markdown |
                    **Ankomst**
                    [[ sensor.stuga1ankomst ]]
                style:
                  color: white
                  background-color: rgba(195,195,195,1)
                  border-radius: 2px
                  border: solid 1px rgba(40,40,40,1)
              - type: custom:card-modder
                card:
                  type: custom:useful-markdown-card
                  content: &markdown |
                    **Ankomst**
                    [[ sensor.stuga2ankomst ]]
                style:
                  color: white
                  background-color: rgba(195,195,195,1)
                  border-radius: 2px
                  border: solid 1px rgba(40,40,40,1)
```
